#!/bin/sh
set -x
MAJOR=1
MINOR=0
PATCH=$(date '+%Y-%m%d-%H%M')

PROJECT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
PARENT_DIR=$( basename -- $PROJECT_DIR )

cd ${PROJECT_DIR}

echo "${MAJOR}.${MINOR}.${PATCH}" > version.txt